package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Message;
import greendao.Parent;
import greendao.messageReceivers;

import greendao.MessageDao;
import greendao.ParentDao;
import greendao.messageReceiversDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig parentDaoConfig;
    private final DaoConfig messageReceiversDaoConfig;

    private final MessageDao messageDao;
    private final ParentDao parentDao;
    private final messageReceiversDao messageReceiversDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        parentDaoConfig = daoConfigMap.get(ParentDao.class).clone();
        parentDaoConfig.initIdentityScope(type);

        messageReceiversDaoConfig = daoConfigMap.get(messageReceiversDao.class).clone();
        messageReceiversDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        parentDao = new ParentDao(parentDaoConfig, this);
        messageReceiversDao = new messageReceiversDao(messageReceiversDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(Parent.class, parentDao);
        registerDao(messageReceivers.class, messageReceiversDao);
    }
    
    public void clear() {
        messageDaoConfig.getIdentityScope().clear();
        parentDaoConfig.getIdentityScope().clear();
        messageReceiversDaoConfig.getIdentityScope().clear();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ParentDao getParentDao() {
        return parentDao;
    }

    public messageReceiversDao getMessageReceiversDao() {
        return messageReceiversDao;
    }

}
