package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import greendao.messageReceivers;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MESSAGE_RECEIVERS.
*/
public class messageReceiversDao extends AbstractDao<messageReceivers, Long> {

    public static final String TABLENAME = "MESSAGE_RECEIVERS";

    /**
     * Properties of entity messageReceivers.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MessageId = new Property(1, long.class, "messageId", false, "MESSAGE_ID");
        public final static Property ParentId = new Property(2, long.class, "parentId", false, "PARENT_ID");
    };

    private DaoSession daoSession;

    private Query<messageReceivers> message_RecipientsQuery;
    private Query<messageReceivers> parent_MessagesReceivedQuery;

    public messageReceiversDao(DaoConfig config) {
        super(config);
    }
    
    public messageReceiversDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MESSAGE_RECEIVERS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MESSAGE_ID' INTEGER NOT NULL ," + // 1: messageId
                "'PARENT_ID' INTEGER NOT NULL );"); // 2: parentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MESSAGE_RECEIVERS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, messageReceivers entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMessageId());
        stmt.bindLong(3, entity.getParentId());
    }

    @Override
    protected void attachEntity(messageReceivers entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public messageReceivers readEntity(Cursor cursor, int offset) {
        messageReceivers entity = new messageReceivers( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // messageId
            cursor.getLong(offset + 2) // parentId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, messageReceivers entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMessageId(cursor.getLong(offset + 1));
        entity.setParentId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(messageReceivers entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(messageReceivers entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "recipients" to-many relationship of Message. */
    public List<messageReceivers> _queryMessage_Recipients(long messageId) {
        synchronized (this) {
            if (message_RecipientsQuery == null) {
                QueryBuilder<messageReceivers> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MessageId.eq(null));
                message_RecipientsQuery = queryBuilder.build();
            }
        }
        Query<messageReceivers> query = message_RecipientsQuery.forCurrentThread();
        query.setParameter(0, messageId);
        return query.list();
    }

    /** Internal query to resolve the "messagesReceived" to-many relationship of Parent. */
    public List<messageReceivers> _queryParent_MessagesReceived(long parentId) {
        synchronized (this) {
            if (parent_MessagesReceivedQuery == null) {
                QueryBuilder<messageReceivers> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ParentId.eq(null));
                parent_MessagesReceivedQuery = queryBuilder.build();
            }
        }
        Query<messageReceivers> query = parent_MessagesReceivedQuery.forCurrentThread();
        query.setParameter(0, parentId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMessageDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getParentDao().getAllColumns());
            builder.append(" FROM MESSAGE_RECEIVERS T");
            builder.append(" LEFT JOIN MESSAGE T0 ON T.'MESSAGE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PARENT T1 ON T.'PARENT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected messageReceivers loadCurrentDeep(Cursor cursor, boolean lock) {
        messageReceivers entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Message message = loadCurrentOther(daoSession.getMessageDao(), cursor, offset);
         if(message != null) {
            entity.setMessage(message);
        }
        offset += daoSession.getMessageDao().getAllColumns().length;

        Parent parent = loadCurrentOther(daoSession.getParentDao(), cursor, offset);
         if(parent != null) {
            entity.setParent(parent);
        }

        return entity;    
    }

    public messageReceivers loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<messageReceivers> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<messageReceivers> list = new ArrayList<messageReceivers>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<messageReceivers> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<messageReceivers> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
